import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex min-h-screen flex-col bg-zinc-50 text-slate-900 dark:bg-black dark:text-white">
        <header className="border-b border-slate-200 bg-white/90 px-6 py-4 shadow-sm backdrop-blur dark:border-slate-800 dark:bg-slate-950/90">
          <nav className="mx-auto flex max-w-6xl items-center justify-between gap-4 text-sm font-medium">
            <div className="flex items-center gap-4">
              <a href="/" className="hover:text-slate-700 dark:hover:text-slate-300">
                Home
              </a>
              <a href="/about" className="hover:text-slate-700 dark:hover:text-slate-300">
                About
              </a>
            </div>
            <div className="flex items-center gap-4">
              <a href="/login" className="hover:text-slate-700 dark:hover:text-slate-300">
                Login
              </a>
              <a href="/register" className="hover:text-slate-700 dark:hover:text-slate-300">
                Register
              </a>
            </div>
          </nav>
        </header>

        <main className="flex-1">{children}</main>
      </body>
    </html>
  );
}
